modLoader = 'lowcodefml'
loaderVersion = '[41,)'
license="MIT"

[[mods]]
  modId="deeper_oceans"
  version="1.0.1a"
  displayName="Deeper Oceans"
  logoFile="pack.png"
  authors="Apollo"
  description='''
  Oceans triple as deep as vanilla's regular oceans!
  '''

  [[dependencies.deeper_oceans]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.deeper_oceans]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
